// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  OutputExpression = 2,
  Not = 8,
  ParenExpression = 9,
  Sequence = 10,
  Dice = 11,
  Cards = 12,
  Num = 13,
  Negative = 14,
  Str = 21
