// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  OutputExpression = 3,
  NumSeq = 4,
  Dice = 5,
  Cards = 6,
  Num = 7,
  Str = 8
