// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^OYQPOOO_QPO'#C_OOQO'#Ce'#CeQYQPOOOmQPO'#C`O_QPO'#CaO!RQPO,58yO_QPO'#CbOOQO'#Cl'#ClOOQO-E6c-E6cO_QPO'#CfO!dQPO,58zOOQO,58z,58zO!lQPO,58zOOQO,58{,58{O_QPO,58{O_QPO,58|O!zQPO1G.eOOQO,58|,58|O#PQPO,59QOOQO-E6d-E6dOOQO1G.f1G.fO#_QPO1G.fOOQO1G.g1G.gOOQO1G.h1G.hO#gOQO'#CdOOQO7+$P7+$POOQO7+$Q7+$QOOOO'#Cg'#CgO#oOQO,59OOOQO,59O,59OOOOO-E6e-E6eOOQO1G.j1G.j",
  stateData: "#w~O^OSPOS~O_PO~OVWOaSOdTOeVO~OVWOaSObYOc[OdTOeVO~Od_Oe`OfaO[Ra_Ra~ObYOceO~ObYOceOd_Oe`O~OgiO~Od_Oe`ObYacYa~ObYOckO~OgnOhlO~OgpOhlO~O",
  goto: "!oaPPPbfffPorx!SPPPP!YTQOR_WPSTVY_`RjaQRORXRQZSSdZfRf]QmiRomQUPQ]SQ^TQbVQcYQg_Rh`",
  nodeNames: "⚠ LineComment Program OutputExpression NumSeq Dice Cards Num Str",
  maxTerm: 24,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "(p~R{OX#xXY#}YZ$tZ^#}^p#xpq#}qr#xrs%is|#x|}%n}!P#x!P!Q%u!Q![&f![#T#x#T#U&x#U#V#x#V#W'V#W#X'^#X#c#x#c#d'e#d#o#x#o#p([#p#q#x#q#r(c#r#y#x#y#z#}#z$f#x$f$g#}$g#BY#x#BY#BZ#}#BZ$IS#x$IS$I_#}$I_$I|#x$I|$JO#}$JO$JT#x$JT$JU#}$JU$KV#x$KV$KW#}$KW&FU#x&FU&FV#}&FV;'S#x;'S;=`(j<%lO#xQ#}OhQR$UY^PhQX^$tpq$t#y#z$t$f$g$t#BY#BZ$t$IS$I_$t$I|$JO$t$JT$JU$t$KV$KW$t&FU&FV$tP$yY^PX^$tpq$t#y#z$t$f$g$t#BY#BZ$t$IS$I_$t$I|$JO$t$JT$JU$t$KV$KW$t&FU&FV$t~%nOg~R%uObPhQR%zPhQ!P!Q%}P&SSPPOY%}Z;'S%};'S;=`&`<%lO%}P&cP;=`<%l%}R&mPVPhQ!Q![&pP&uPVP!Q![&pR&}PhQ#g#h'QP'VOfPR'^OePhQR'eOdPhQR'jPhQ#i#j'mP'pP#h#i'sP'vP#d#e'yP'|P#i#j(PP(SP#h#i(VP([O_PR(cOaPhQR(jOcPhQQ(mP;=`<%l#x",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
